lib/NetKAT_LocalCompiler.ml
Some basic optimizations. No new features:
- CPS the policy compiler
- CPS the variable-order heuristic
- Better compilation of star
=> Optimizations

async/Async_NetKAT_Controller.ml, async/Async_NetKAT_Controller.mli
Added a set_order function which can be used to set the ordering the compiler should use.
=> Controller order

lib/NetKAT_LocalCompiler.ml, test/FlowTable_Generation.ml
These fix small issues with the compiler.
=> Compiler bugfix

lang/python/frenetic/__init__.py, lang/python/frenetic/examples/discovery/probe.py, lang/python/frenetic/examples/discovery/topology.py, lang/python/frenetic/examples/learning.py
Increased switch data in probe to 64 bits, increased probe collection time to 30 seconds (necessary on our network of 30 switches) and added some backwards-compatible support for Frenetic http connections to address other than localhost:9000.
=> Fixes Issue #423, Topology and Dell Switches

lib/Frenetic_GroupTable0x04.ml, lib/Frenetic_GroupTable0x04.mli, lib/Frenetic_NetKAT_Compiler.ml, lib/Frenetic_NetKAT_Compiler.mli, lib/Frenetic_OpenFlow.ml, lib/Frenetic_OpenFlow.mli, lib/Frenetic_OpenFlow0x04.ml, lib/Frenetic_OpenFlow0x04.mli, lib/Frenetic_Vlr.ml, lib/Frenetic_Vlr.mli
This adds a bunch of `with sexp`'s to various files and implements a `to_string` function for group tables.
@jcollard I think you are working on the group tables and openflow 0x04? Can you take a look?
=> Group table printing

async/Frenetic_NetKAT_Updates.ml
=> Remove now-illegal printfs from async code

lib/Frenetic_NetKAT_Json.ml
This should fix the JSON inconsistencies mentioned in https://github.com/frenetic-lang/frenetic/issues/450
=> Fix JSON inconsistencies

lang/python/frenetic/syntax.py, lib/Frenetic_Fdd.ml, lib/Frenetic_Fdd.mli, lib/Frenetic_Hashcons.ml, lib/Frenetic_Hashcons.mli, lib/Frenetic_NetKAT_Compiler.ml, lib/Frenetic_NetKAT_Json.ml, lib/Frenetic_NetKAT_Semantics.ml, lib/Frenetic_Util.ml, lib/Frenetic_Util.mli, lib/Frenetic_Vlr.ml, lib/Frenetic_Vlr.mli
Various tweaks of the compiler code:
* moved to Core.Std
* removed dead code
* hide FDD implementation to avoid nasty bugs
* fixed bug in cache-clearing function
* global memoization insted of local memoization
* ...
=> Compiler tuning

async/Frenetic_Ox.ml, async/Frenetic_Ox.mli, opam
Pulled Platform to be a top level module in Frenetic_Ox.
=> Initial refactor to fix Ox Platform visibility

lib/Frenetic_NetKAT_Parser.ml, syntax/Frenetic_Syntax_Extension_Parser.ml
Fixed Syntax Extension parser to exactly match the more up-to-date "file" parser.  Also corrected a small bug in file parser.
=> Square Up Parser Syntax

lib/Frenetic_NetKAT_Parser.cppo.ml
Addresses #499 @smolkaj If you could check this when you have a moment ... it works but I don't know if it might be wrecking performance.
=> Fixed Bad File Descriptor on Dump Subcommand

examples/bug-#497-may-2016.kat, frenetic/Dump.ml, lib/Frenetic_NetKAT_Compiler.mli
Until now, the dump-fdd flag didn't actually dump FDDs...
=> Implements command to dump FDDs

examples/begin-end.kat, lib/Frenetic_NetKAT_Lexer.ml, lib/Frenetic_NetKAT_Parser.cppo.ml
Adds OCaml-style `begin` ... `end` syntax as discussed in #494.
=> Begin end syntax

lib/Frenetic_NetKAT_SDN_Json.ml
=> Fix Mod(EthDst()) in PacketOut

lib/Frenetic_NetKAT_Compiler.mli
This exposes the FDD-related functionality (fold, map, etc. over FDDs).
=> expose FDD functionality

lib/Frenetic_NetKAT_Virtual_Compiler.ml
=> Bug fix from old branch

lib/Frenetic_NetKAT_Compiler.ml
=> document dedup (after forgetting its purpose and painfully reconstructing it)

.travis.docgen.sh, .travis.yml
=> more jbuilder (do not merge yet)

frenetic.opam, src/exe/Dump.ml, src/exe/jbuild, src/exe/main.ml, src/exe/openflow.ml, src/lib/async/Compile_Server.ml, src/lib/async/Http_Controller.ml, src/lib/async/OpenFlow0x01_Plugin.ml, src/lib/async/OpenFlow0x04_Plugin.ml, src/lib/async/jbuild, src/lib/kernel/Network.ml, src/lib/kernel/OpenFlow0x01.ml, src/lib/kernel/Topology.ml, src/lib/kernel/jbuild, src/lib/netkat/Fdd.ml, src/lib/netkat/Global_compiler.ml, src/lib/netkat/Local_compiler.ml, src/lib/netkat/Semantics.ml, src/lib/netkat/jbuild
the new JS libraries make some breaking changes; fix them
=> upgrade to jane-street v0.10

exe/dump.ml, exe/icfp.ml, exe/jbuild, exe/topo.ml, lib/kernel/Network.ml, lib/kernel/Network.mli, src/Params.ml, src/Symbolic.ml, src/Topology.ml, src/schemes.ml
merge in ICFP hacks
TODO: clean up
=> Mc decision icfp

examples/fall-through-optimization.kat, examples/fall-through-optimization2.kat, src/lib/netkat/Fdd.ml, src/lib/netkat/Fdd.mli, src/lib/netkat/Global_compiler.ml, src/lib/netkat/Local_compiler.ml, src/lib/netkat/Syntax.ml, src/lib/netkat/Syntax.mli, src/lib/netkat/Vlr.ml, src/lib/netkat/Vlr.mli
* use inline records for better readability
* derive hash functions automatically
* added "all-false" branch to FDDs; this makes them slightly more canonical
=> Somewhat improved FDDs

src/lang/python/frenetic/examples/learning.py
learning application must flood packet with unknown destination, not source #619
=> flood unknow dst
