frenetic-lang/frenetic

- async/Async_NetKAT_Controller.ml
- lib/NetKAT_LocalCompiler.ml
- lib/NetKAT_LocalCompiler.mli
- lib/NetKAT_Vlr.ml
- lib/NetKAT_Vlr.mli
- test/FDD_Cache.ml
- test/Test.ml
In addition to completely preserving and clearing the cache, the
local compiler can now clear everything except an the data for
an existing FDD.
This fixes an issue with the controller, where FDD-operations are
used to compare the new and old FDD after compile is called.
Clearing the cache completely invalidates the old FDD. Using
the new `Preserve option, we can clear all the auxiliary data
used to create the old FDD but keep it intact.
> New cache-clearing policy

- README.md
The previous example doesn't work anymore. I've modified the example and tested with Mininet. It worked.
> Fixed Usage Example in README.md

- Makefile
For some reason the line to generate `setup.data` got dropped from the Makefile. This adds it back.
> Readded setup.data line to Makefile

- lang/python/frenetic/__init__.py
- lang/python/frenetic/examples/discovery.py
- lang/python/frenetic/examples/discovery/discovery.py
- lang/python/frenetic/examples/discovery/flood_switch.py
- lang/python/frenetic/examples/discovery/routing.py
- lang/python/frenetic/examples/discovery/state.py
- lang/python/frenetic/examples/discovery/topology.py
- lang/python/frenetic/examples/firewall.py
- lang/python/frenetic/syntax.py
*Warning*. In Python, the True and False policies have been renamed to Id and Drop. This is to avoid clashing with Python's builtin True and False. You can always use the constants `true` and `false` (lowercase.)
> Cherry-picking Joe's edits

- async/Frenetic_OpenFlow0x01_Controller.ml
Actually send the message in `Frenetic_OpenFlow_Controller.send_txn`.
Fixes #414.
> Fix port_stats bug

- async/Frenetic_OpenFlow0x01_Controller.ml
It's legal for switches to send msgs between the features request and response, but our OpenFlow state machine was crashing (assert false). We now just ignore them.
Alternative solution would be to create a queue and save them until the handshake is finished, then deliver them.
> Don't crash on msgs between Features req and resp

- async/Frenetic_NetKAT_Controller.ml
- async/Frenetic_NetKAT_Controller.mli
- lib/Frenetic_NetKAT_Json.ml
- lib/Frenetic_NetKAT_Json.mli
- lib/Frenetic_OpenFlow0x01.ml
- lib/Frenetic_OpenFlow0x01.mli
Returns list of port stats by Json instead of one object.  If port is non-existent or stats are not available, simply sends back [].  
Also handles "get all port stats for each port on a switch" for free if you send port=65535 (as per OpenFlow 1.0 specs).
> Properly parse 0-n port stats replies

- lib/Frenetic_OpenFlow.ml
Example table:
```
+------------------------------------------+
| Switch 1 | Pattern | Action              |
|------------------------------------------|
| InPort = 0         | SetField(vlan, 7)   |
|                    | Output(2)           |
|                    | + SetField(vlan, 3) |
|                    | Output(4)           |
|------------------------------------------|
|                    |                     |
+------------------------------------------+
```
The `+` signals a multicast . Not super pretty, but it does the job. I'm open for improvements.
@jcollard: What do you think?
> explicitly label multicast in asci-tables

- async/Frenetic_Http_Controller.ml
As reported in issue #488, certain HTTP problems throw confusing errors into the log.  In particular:
1. App issues GET /client_id/events.  
1.  Frenetic blocks on this request until an event occurs
1.  App dies
1.  Frenetic gets an event of some sort, and tries to return to the HTTP client as a response to the GET.  It throws a "writer fd unexpectedly closed" error to the log (but keeps going).
The fix simply watches for this error and ignores it if it occurs.  Other HTTP errors continue to be logged.
> Swallow writer exceptions instead of printing to log

- async/Frenetic_NetKAT_Controller.ml
- async/Frenetic_NetKAT_Updates.ml
- async/Frenetic_OpenFlow0x01_Controller.ml
- async/Frenetic_OpenFlow0x01_Controller.mli
- frenetic/openflow.ml
- lang/python/frenetic/__init__.py
- lang/python/frenetic/examples/firewall.py
- lang/python/frenetic/examples/port_count.py
Frenetic adds a transactional layer for several request-response OpenFlow queries like port_stats.  The layer had a few problems:
- It didn't actually send the request.  It just waited for the response that would never show up.
- It was trying to send Deferreds over a TCP socket from the openflow process to the Frenetic process.   Async would try to deserialize the Deferred message, get really confused, and segfault.  
The fix makes sure all Deferreds are determined before sending the results over the wire.  /port_stats now works.  Need to test other transactional stuff like queries (flow_stats) before merging in.
> Fix Request-Response OpenFlow Transactions

- examples/pipe_and_query.kat
- lib/Frenetic_NetKAT_Lexer.ml
- lib/Frenetic_NetKAT_Lexer.mli
- lib/Frenetic_NetKAT_Parser.cppo.ml
NetKAT now supports syntax for pipes and queries:
```
filter port = 1; port := pipe("ctrl") |
filter port = 2; port := query("qry") |
filter port = 3; port := 1
```
> Added Pipe and Query to Raw NetKAT Syntax

- lang/python/frenetic/__init__.py
- lang/python/frenetic/examples/discovery/flood_switch.py
- lang/python/frenetic/examples/discovery/topology.py
- lang/python/frenetic/examples/firewall.py
- lang/python/frenetic/examples/flood_switch.py
- lang/python/frenetic/examples/learning.py
- lang/python/frenetic/examples/load_balancer.py
- lang/python/frenetic/examples/packet_in_out.py
- lang/python/frenetic/examples/repeater.py
- lang/python/frenetic/examples/silly.py
- lang/python/frenetic/net_utils.py
- lang/python/frenetic/packet.py
- lang/python/frenetic/syntax.py
- lang/python/frenetic/tests/test_packet.py
- lang/python/frenetic/tests/test_syntax.py
Added the following syntactic sugar to Python bindings.  All are backwards compatible.  
* `SetPort(n)` should be usable in a Packet Out as a synonym for `Output(Physical(n))`.  Other Set's (synonyms for Mod(Field())) can be used in either a Packet Out action list or a NetKAT policy.
* A `Seq` of policies should be able to used in a Packet Out command as a synonym for a list of policies.  
* `SetPort(p1, p2, ... pn)` should be a synonym for `SetPort(p1) | SetPort(p2) | ... | SetPort(pn)`.  
* Parsing a packet and testing header values using RYU Packet Library treads the same ground as a NetKAT predicate.  You should be able to use NetKAT predicates directly in the controller's Packet In handler - e.g. `self.matches(payload, PortEq(23) & EthTypeEq(0x800))`.  That way you have to only learn …
> More Python Extensions

- .travis.yml
To be honest, automatic doc gen by Travis has worked exactly once since it was installed on March 10.  Though the API docs were not installed, they didn't cause a build failure ... unitl June 15 when the authors of travis-docgen.sh attempted a fix which may hva fixed other problems but broke our build.  
This is an attempt to skirt around the Unbound Variable error mentioned in #516.  If it doesn't work, I'll just pull API doc gen out until they can get it fixed correctly.
> Attempt Simple Fix for Travis Doc Gen

- async/Frenetic_OpenFlow0x04_Plugin.ml
- lib/Frenetic_NetKAT_Compiler.ml
This code fixes a bug related to generation of multiple tables in OpenFlow 1.3. In particular, FDD Leaf nodes were not being handled correctly.
> Bug fixes 

- lib/Frenetic_OpenFlow0x04.ml
Currently, a `None` value for the `mfOut_port` field of a `flowMod` is serialized to `0` during marshaling, but `0` is a valid port number. It should be serialized to `OFPP_ANY` to match regardless of out_port. I believe `mfOut_group` has the same issue.
Due to this, the `delete_all_flows` convenience flowMod doesn't delete all flows.
This fix causes a couple unit tests to break (some marshaling tests are already breaking), but I wanted to bring it up before continuing.
Todo:
> Fix OpenFlow0x04 FlowMod.marshal

- lib/Frenetic_OpenFlow0x04.ml
Without setting these bits, matches against and writes to a packet's vlan id are ignored.
> Set OFPVID_PRESENT bits in marshaling of OxmVlanVId fields in OF1.3

- async/Frenetic_Ox.ml
The Ox controller was not invoking the programmer-supplied handler
when switches disconnect.
> Fix bug with `Frenetic_Ox.switch_disconnected` handler.

- lib/Frenetic_NetKAT_Lexer.ml
- lib/Parser.cppo.mly
We missed this case during the ppx rewrite. `drop` vtopos were still passing, but vlinks weren't being parsed.
> Fix parsing vlinks after ppx change

- examples/automata/README.md
- examples/automata/unrollable.kat
- examples/automata/unrolled.kat
- frenetic/Dump.ml
- lib/Frenetic_Fdd.ml
- lib/Frenetic_Fdd.mli
- lib/Frenetic_NetKAT.ml
- lib/Frenetic_NetKAT.mli
- lib/Frenetic_NetKAT_Compiler.ml
- lib/Frenetic_NetKAT_Compiler.mli
- lib/Frenetic_NetKAT_Json.ml
- lib/Frenetic_NetKAT_Lexer.ml
- lib/Frenetic_NetKAT_Optimize.ml
- lib/Frenetic_NetKAT_Pretty.ml
- lib/Frenetic_NetKAT_Semantics.ml
- lib/Parser.cppo.mly
* extends `frenetic dump` with a command to dump automata
* exposes `dup` in NetKAT source language, to allow experimenting with automata more easily.
* fixes & improves pretty printing of symbolic NetKAT automata
* add directory for automata examples
> polished symbolic automata interface (for @Jaxan)

- frenetic/main.ml
- lib/async/OpenFlow0x01_Plugin.ml
- lib/base/std/Topology.ml
- lib/base/std/Topology.mli
- lib/netkat/Fdd.ml
- lib/netkat/Fdd.mli
- lib/netkat/Json.ml
- lib/netkat/Lexer.cppo.sedlex.ml
- lib/netkat/Parser.cppo.mly
- lib/netkat/Parser.ml
- lib/netkat/Parser.mli
- lib/netkat/Portless_Compiler.ml
- lib/netkat/Portless_Compiler.mli
- lib/netkat/Pretty.ml
- lib/netkat/Semantics.ml
- lib/netkat/Semantics.mli
- lib/netkat/Syntax.ml
- lib/netkat/Syntax.mli
- lib/netkat/jbuild
Portless NetKAT is a modified version of the NetKAT language for defining policies without ports. The language, takes the regular NetKAT and replaces the `Switch` and `Port` header with `Location` and `From` headers. Here, both `Location` and `From` can take values that either represent a host or a switch. 
Topology:
```
[h1]----1[s1]2---2[s2]1----[h2]
```
Portful Policy:
```
if sw = 1 then
if pt = 1 then pt := 2
else if pt = 2 then pt := 1
else drop
else if sw = 2 then
if pt = 1 then pt := 2
else if pt = 2 then pt := 1
else drop
else drop
```
Equivalent Portless Policy:
```
if loc = "s1" then
if from = "h1" then loc := "s2"
else if from = "s2" then loc := "h1"
else drop
if loc = "s2" then
if from = "h2" then loc := "s1"
else if from = "s1" then loc := "h2"
else drop
else drop
```
As the …
> Portless NetKAT

- lib/netkat/jbuild
Find `ppx_sedlex` binary more reliably.
> fix #590: more robust way to invoke ppx_sedlex (not supported by jbuilder)

- frenetic.opam
This should remove the need to recompile frenetic when Menhir is updated.
Since frenetic doesn't use Menhir's `--table` mode,  it doesn't depend on MenhirLib, so this should be OK.
> Note that Menhir is only a build dependency.

- frenetic.opam
Cstruct 4.0 makes some breaking changes; in particular, it factors out s-expression support into a separate library. 
This addresses #633
> Pin cstruct to < 4.0.0

- frenetic.opam
- src/lib/kernel/OpenFlow.ml
- src/lib/kernel/OpenFlow0x01.ml
- src/lib/kernel/OpenFlow0x04.ml
- src/lib/kernel/Packet.ml
- src/lib/kernel/dune
- src/lib/netkat/Domain.ml
- src/lib/netkat/Domain.mli
- src/lib/netkat/Global_compiler.ml
- src/lib/netkat/Global_compiler.mli
- src/lib/netkat/Packet.ml
- src/lib/netkat/Packet.mli
- src/lib/netkat/Vlr.ml
- src/lib/netkat/Vlr.mli
Fixed some dependencies:
* upgrade to cstruct 4.0.0
* upgrade to yojson 1.7.0
Improved some interfaces:
* Global compiler now exposes automaton type, safely (using `private`)
* Use `Hashtbl.foo` instead of specialized `Tbl.foo` in various places.
Added two new modules:
* Packet.ml: Models packets as maps from fields to integers.
* Domain.ml: The domain of a FDD/Automaton/... is the set of fields that appear in it, together with the set of values that appear with each field (in a test or a modification).
> New Domain and Packet modules; fixes
